### ISSUE TITLE
"Cannot add client, conf is null" error

### ISSUE THREAD

**Issue by lrivera8** [upnext/BeaconControl_Android_SDK#2]
Getting "Cannot add client, conf is null" error after startScan.

I am using the client_id and secret_id from the platforma, and the email I registered with as user_id.

Logs:

D/BeaconParser: Parsing beacon layout: m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
D/BeaconSDK~BeaconService: Start scan.
D/BeaconSDK~BeaconService: Cannot add client, conf is null.
D/BeaconSDK~BeaconService: onBeaconServiceConnect
D/BeaconSDK~BeaconControlManagerImpl: Error in getToken task.
W/BeaconSDK~BeaconControlManagerImpl: Token has not been retrieved.
D/BeaconSDK~HttpCallMediator: IO_ERROR
D/BeaconSDK~BeaconServiceHelper: Error in getConfigurations task, IO_ERROR

**Comment by danielnow** [comment]
Thanks for reporting this issue. We investigated it and introduced some changes.

Please, download updated BeaconsControlSDK-1.0.aar file and check the problem is solved now.
