### ISSUE TITLE
Getting styles error while build

### ISSUE THREAD

**Issue by lrivera8** [upnext/BeaconControl_Android_SDK#5]
Hi again,
I updated the .aar file, but now I am getting an error while building the application:

AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027Theme.AppCompat.Light.DarkActionBar\u0027.","sources":[{"file":"/Users/lrivera/Documents/Projectes_Android/BeaconControl/app/src/main/res/values/styles.xml","position":{"startLine":1}}],"original":""}
AGPBI: {"kind":"error","text":"No resource found that matches the given name: attr \u0027colorAccent\u0027.","sources":[{"file":"/Users/lrivera/Documents/Projectes_Android/BeaconControl/app/src/main/res/values/styles.xml","position":{"startLine":7,"startColumn":20,"startOffset":317,"endColumn":31,"endOffset":328}}],"original":""}
AGPBI: {"kind":"error","text":"No resource found that matches the given name: attr \u0027colorPrimary\u0027.","sources":[{"file":"/Users/lrivera/Documents/Projectes_Android/BeaconControl/app/src/main/res/values/styles.xml","position":{"startLine":5,"startColumn":20,"startOffset":187,"endColumn":32,"endOffset":199}}],"original":""}
AGPBI: {"kind":"error","text":"No resource found that matches the given name: attr \u0027colorPrimaryDark\u0027.","sources":[{"file":"/Users/lrivera/Documents/Projectes_Android/BeaconControl/app/src/main/res/values/styles.xml","position":{"startLine":6,"startColumn":20,"startOffset":248,"endColumn":36,"endOffset":264}}],"original":""}

Has something to do with the compile sdk?

Thank you in advance.

**Comment by lrivera8** [comment]
Hi there,
I found out adding compile 'com.android.support:appcompat-v7:22.2.0' in the dependecies fixed the problem.

But now getting different error: E/BeaconManager﹕ Cannot contact service to set scan periods.

Any idea?

**Comment by danielnow** [comment]
Hi Irivera8,

Thank you very much for your feedback.

We are working on solving this issue. Could you provide us the information on which device and Android version you have performed the tests?

Have you also checked the issue on another devices?

Thank you.

**Comment by lrivera8** [comment]
Hi danielnow, 
Last time I tried it worked, if I find something else I will tell you.

Thank you!
